<?php

/**
 * @file
 * Contains chatbox_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function chatbox_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chatbox_api module.
    case 'help.page.chatbox_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('API for chatbox and Personal Assistant') . '</p>';
      return $output;

    default:
  }
}
