<?php

/**
 * @file
 * Contains chatbox_alexa.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function chatbox_alexa_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chatbox_alexa module.
    case 'help.page.chatbox_alexa':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Alexa implementation for Chatbx API') . '</p>';
      return $output;

    default:
  }
}
